<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Introducción a python</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Profesor: M.en.C. César Carreón</i></h5>
    <h5 align="center"><i>Ayudante: Jesús Iván Coss Calderón</i></h5>
    <h5 align="center"><i>Materia: Análisis numérico</i></h5>
  </font>

**Objetivo general**

* Aprender los fundamentos de los algoritmos de sustitución.

**Objetivos particulares**

* Conocer el algoritmo de sustitución hacia delante.
* Conocer el algoritmo de sustitución hacia atras.

<a name='c1'></a>

## Contenido

- [Introducción](#1)
- [Sustitución hacia delante](#2)
    - [Comprobación](#2-1)
- [Sustitución hacia atras](#3)
    - [Comprobación](#3-1)
    

<a name='1'></a>

# Introducción 

<a name='2'></a>

# Sustitución hacia delante

[regresar al contenido](#c1) 

In [10]:
import numpy as np

In [11]:
def sustDelante(L,b):
    n=len(L)
    y=np.empty_like(b)
    y[0] = b[0]/L[0][0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(0,i):
            y[i] -= L[i][j]*y[j]
        y[i] /= L[i][i]
        
    return y

<a name='2-1'></a>

# Comprobación

[regresar al contenido](#c1) 

In [12]:
b=np.ones(3)
up= np.array([[1,0,0],[-2,1,0],[-1,3,1]])

In [13]:
res1=sustDelante(up,b)
res1

array([ 1.,  3., -7.])

In [14]:
np.linalg.solve(up,b)

array([ 1.,  3., -7.])

<a name='3'></a>

# Sustitución hacia atras

[regresar al contenido](#c1) 

In [15]:
def sustAtras(U,y):
    n=len(U)
    x=np.empty_like(y)
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] -= U[i][j]*x[j]
        x[i] /= U[i][i]

    return x

<a name='3-1'></a>

# Comprobación

[regresar al contenido](#c1) 

In [16]:
Low=np.array([[-4,-3,1],[0,5,1],[0,0,3]])
b=np.ones(3)

In [17]:
res=sustAtras(Low,b)
res

array([-0.26666667,  0.13333333,  0.33333333])

In [18]:
np.linalg.solve(Low,b)

array([-0.26666667,  0.13333333,  0.33333333])